components/Dashboard.tsx(550, 62): Type '{ content: Element; unit: string; }' is not assignable to type 'IntrinsicAttributes & Omit<Props<ValueType, NameType>, PropertiesReadFromContext> & { ...; }'. Property 'unit' does not exist on type 'IntrinsicAttributes & Omit<Props<ValueType, NameType>, PropertiesReadFromContext> & { ...; }'. components/Dashboard.tsx(583, 62): Type '{ content: Element; unit: string; }' is not assignable to type 'IntrinsicAttributes & Omit<Props<ValueType, NameType>, PropertiesReadFromContext> & { ...; }'. Property 'unit' does not exist on type 'IntrinsicAttributes & Omit<Props<ValueType, NameType>, PropertiesReadFromContext> & { ...; }'.